# Generated by Django 3.2.1 on 2021-05-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('cust_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField()),
                ('isAuthorized', models.IntegerField()),
                ('last_updated_date', models.DateField(auto_now=True)),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNo', models.CharField(max_length=16)),
                ('bank', models.CharField(choices=[('hdfc', 'HDFC'), ('icici', 'ICICI'), ('kotak', 'Kotak Mahindra'), ('pnb', 'PNB'), ('bob', 'Bank Of Badora'), ('sbi', 'SBI'), ('other', 'Other')], max_length=30)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdetails')),
            ],
        ),
    ]
