# Generated by Django 3.2.1 on 2021-05-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userbankdetails_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankdetails',
            name='bank',
            field=models.CharField(choices=[('hdfc', 'HDFC'), ('icici', 'ICICI'), ('kotak', 'Kotak Mahindra'), ('pnb', 'PNB'), ('bob', 'Bank Of Badora'), ('sbi', 'SBI'), ('paytm', 'Paytm'), ('other', 'Other')], max_length=30),
        ),
    ]
